use_frameworks!

target 'MRArticleViewController_Example' do
  pod 'MRArticleViewController', :path => '../'

  target 'MRArticleViewController_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
    pod 'Nimble', '~> 3.0'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
